travis:
  secure:
    BINSTAR_TOKEN: X6JI5uUcTS9IAjRAgUzIlq2rLydSU4pbgt3Y5O5pyqzGfMKnria23dE8Y7n/JKQb6o7MIs7Xgn7P1SGP/1RVYtKsxesQXqvle9Gj2wYCRJCnft/8goFHq3R2x7Q1YacKCjnIFXhOFkw4lZ5vplKz0dXX+V+gFQqnCNky4H7oBStlLgeboHsA5hDEKL0E4USXkMNR3QPKZxQSJBNAazopwyiGTMCVUE8igJTeYbduBOpxx+ye0KpvLJRN/+WfrqV+2c4BCmUse/CG6ihAKOmLk2ZMj9ePvHW5Zf2Jr4RxsypB9QeirdrmFgKRXKkrIIQCqlptbNwegJClDNUoY9MhcxROEElsyuzlT0/0RZgn87A2v6AQLbI2WSZzaKOjLc1Y6S8NHlZ6QhKCJeDZbZpUb3IqjeCPEUNnNUPKjwiaXZh52cMRX5YNeNG+LKzgAMnZ9eyLse+p7OH15aPGj2+Z+/UNqmjSWzMRp5pRP0F8bxzR6wSM4KUNW1YN0Bkf06dB9BS1U31HAsbJu5M7KJjhh2XNj/5jkqGnn/Aso+b1y+L03zBe3drgaY4oGQfT9FSnaB59H06rdGPRjxI1FP9CGmqOd+sJBPXc6+1uXhybR4oThe1DqHPutGogdh93nnewFk0bVQ62QMn2ZvQK6i9tfV+773yvnlOsvOOBOk1wOiE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
