travis:
  secure:
    BINSTAR_TOKEN: nGlRNAZgRyIVDMIn7OwoNPo7T7Z1Jy2fIzJOQ4KwbuMSSNBDB6JjDot/96gj7I5Y/CaqrW13HBSMDXhepnAcBqJ83VMfkscdYhPnETU9+m9D9sSdMS7LfMq2z+TEQtvzoYwkSH2WqRsFAQNSqFi09dF4YRRjYKETfQ0IRmPhgall/OmC4XV0OXA8opt+MLpYfokjUyvg6cPW7WQt0ZCLikfQJmIfNCtk94A4yFdfA+LRiZYe9UYLqDcxtuL941GxrWrihzQAwC2aiJuV5MiuSQa3/fdymeuTAVEmXiC0Y6eRyY3FoGlnDi7/heV5PP7HsUNXFeCz3BEIALpOo5QZfkJm89fptMqSk4Fjguiqi+a1QqJK2QDy9vYb5Cat7LKh0Y6ErvDJngVgVPTK/RSnG6ilCEFlTuSzpUhQ4/v+UUyhuDuqUahT1zyAcnoo6sLettqO3rOkocEeeXWz7vb3BhfhkJ9qp7D7BTkZ4WbVo2TNE+0NAUy0tl5g9Kyg9eMbcav5cGkmHnDR77pv6AZCk3XJc/uW1Fs/8U0GfByEzzQW3g5xZ4mQqgRwV43fqYtNCCm5vfrbTrIgANSA+0YxxsNw4yyg6FpDhtSRusOScm7JasWhS0K5owxEc3sh7VeNJ6wRZTNG8HdnmBUQQcP/W52zyFQGUPTytzEdHqQSHig=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
